# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGoogleSearch1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_googleSearch1(self):
    # Test name: googleSearch1
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://www.google.co.in/")
    # 2 | setWindowSize | 1024x728 |  | 
    self.driver.set_window_size(1024, 728)
    # 3 | selectFrame | index=1 |  | 
    self.driver.switch_to.frame(1)
    # 4 | click | css=.rr4y5c |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".rr4y5c").click()
    # 5 | selectFrame | relative=parent |  | 
    self.driver.switch_to.default_content()
    # 6 | click | name=q |  |

    elementSearch = self.driver.find_element_by_name("q")
    # elementSearch = self.driver.find_element(By.NAME, "q")
    elementSearch.click()
    # 7 | type | name=q | learn python | 
    elementSearch.send_keys("learn python")
    # 8 | sendKeys | name=q | ${KEY_ENTER} | 
    elementSearch.send_keys(Keys.ENTER)
  
